<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Carbon;

class UsuarioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $agora = Carbon::now();

        $atletas = [
            [
                'nomeCompletoUsuario' => 'Lucas Ferreira da Silva',
                'emailUsuario' => 'lucasf@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '2002-05-14',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 178.5,
                'pesoKg' => 72.3,
                'peDominante' => 'Direito',
                'maoDominante' => 'Destro',
                'generoUsuario' => 'Masculino',
                'estadoUsuario' => 'São Paulo',
                'cidadeUsuario' => 'Campinas',
                'created_at' => $agora->copy()->subMonths(5)->toDateTimeString(),
                'updated_at' => $agora->copy()->subMonths(5)->toDateTimeString(),
            ],
            [
                'nomeCompletoUsuario' => 'Mariana Costa Oliveira',
                'emailUsuario' => 'maricosta@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '2004-11-09',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 182.0,
                'pesoKg' => 68.0,
                'peDominante' => 'Direito',
                'maoDonante' => 'Destro',
                'generoUsuario' => 'Feminino',
                'estadoUsuario' => 'Minas Gerais',
                'cidadeUsuario' => 'Belo Horizonte',
                'created_at' => $agora->copy()->subMonths(5)->toDateTimeString(),
                'updated_at' => $agora->copy()->subMonths(5)->toDateTimeString(),
            ],
            [
                'nomeCompletoUsuario' => 'Rafael Andrade Lima',
                'emailUsuario' => 'rafael.a@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '1999-02-25',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 174.0,
                'pesoKg' => 69.5,
                'peDominante' => 'Direito',
                'maoDominante' => 'Destro',
                'generoUsuario' => 'Masculino',
                'estadoUsuario' => 'Rio de Janeiro',
                'cidadeUsuario' => 'Niterói',
                'created_at' => $agora->copy()->subMonths(5)->toDateTimeString(),
                'updated_at' => $agora->copy()->subMonths(5)->toDateTimeString(),
            ],
            [
                'nomeCompletoUsuario' => 'Beatriz Santos Nogueira',
                'emailUsuario' => 'bia.nog@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '2005-08-12',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 170.0,
                'pesoKg' => 60.0,
                'peDominante' => 'Direito',
                'maoDominante' => 'Destro',
                'generoUsuario' => 'Feminino',
                'estadoUsuario' => 'Paraná',
                'cidadeUsuario' => 'Curitiba',
                'created_at' => $agora->copy()->subMonths(4)->toDateTimeString(),
                'updated_at' => $agora->copy()->subMonths(4)->toDateTimeString(),
            ],
            [
                'nomeCompletoUsuario' => 'João Victor Mendes',
                'emailUsuario' => 'joaovm@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '2001-03-22',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 185.0,
                'pesoKg' => 80.0,
                'peDominante' => 'Direito',
                'maoDominante' => 'Destro',
                'generoUsuario' => 'Masculino',
                'estadoUsuario' => 'Bahia',
                'cidadeUsuario' => 'Salvador',
                'created_at' => $agora->copy()->subMonths(4)->toDateTimeString(),
                'updated_at' => $agora->copy()->subMonths(4)->toDateTimeString(),
            ],
            [
                'nomeCompletoUsuario' => 'Carla Lima Souza',
                'emailUsuario' => 'carlinha@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '2003-07-30',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 177.0,
                'pesoKg' => 65.0,
                'peDominante' => 'Direito',
                'maoDominante' => 'Destro',
                'generoUsuario' => 'Feminino',
                'estadoUsuario' => 'São Paulo',
                'cidadeUsuario' => 'Santos',
                'created_at' => $agora->copy()->subMonths(4)->toDateTimeString(),
                'updated_at' => $agora->copy()->subMonths(4)->toDateTimeString(),
            ],
            [
                'nomeCompletoUsuario' => 'Eduardo Rocha Lima',
                'emailUsuario' => 'edu.rocha@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '1998-12-01',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 180.0,
                'pesoKg' => 75.0,
                'peDominante' => 'Direito',
                'maoDominante' => 'Destro',
                'generoUsuario' => 'Masculino',
                'estadoUsuario' => 'Pernambuco',
                'cidadeUsuario' => 'Recife',
                'created_at' => $agora->copy()->subMonths(3)->toDateTimeString(),
                'updated_at' => $agora->copy()->subMonths(3)->toDateTimeString(),
            ],
            [
                'nomeCompletoUsuario' => 'Larissa Gomes Pinto',
                'emailUsuario' => 'lari.pinto@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '2006-09-05',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 165.0,
                'pesoKg' => 55.0,
                'peDominante' => 'Direito',
                'maoDominante' => 'Canhoto',
                'generoUsuario' => 'Feminino',
                'estadoUsuario' => 'Rio Grande do Sul',
                'cidadeUsuario' => 'Porto Alegre',
                'created_at' => $agora->copy()->subMonths(2)->toDateTimeString(),
                'updated_at' => $agora->copy()->subMonths(2)->toDateTimeString(),
            ],
            [
                'nomeCompletoUsuario' => 'Pedro Henrique Almeida',
                'emailUsuario' => 'pedroha@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '2000-01-10',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 183.0,
                'pesoKg' => 77.0,
                'peDominante' => 'Direito',
                'maoDominante' => 'Destro',
                'generoUsuario' => 'Masculino',
                'estadoUsuario' => 'Ceará',
                'cidadeUsuario' => 'Fortaleza',
                'created_at' => $agora->copy()->subMonths(1)->toDateTimeString(),
                'updated_at' => $agora->copy()->subMonths(1)->toDateTimeString(),
            ],
            [
                'nomeCompletoUsuario' => 'Sofia Reis Martins',
                'emailUsuario' => 'sofiamartins@gmail.com',
                'senhaUsuario' => Hash::make('123456'),
                'dataNascimentoUsuario' => '2007-10-15',
                'fotoPerfilUsuario' => null,
                'fotoBannerUsuario' => null,
                'alturaCm' => 160.0,
                'pesoKg' => 50.0,
                'peDominante' => 'Direito',
                'maoDominante' => 'Destro',
                'generoUsuario' => 'Feminino',
                'estadoUsuario' => 'Santa Catarina',
                'cidadeUsuario' => 'Florianópolis',
                'created_at' => $agora->toDateTimeString(),
                'updated_at' => $agora->toDateTimeString(),
            ],
        ];

        DB::table('usuarios')->insert($atletas);
    }
}
